const CANVAS_HEIGHT = 800;
const CANVAS_WIDTH = 1500;
const DOWN_ARROW = 40;
const UP_ARROW = 38;
const LEFT_ARROW = 37;
const RIGHT_ARROW = 39;
let bgImage;
let thePig;
let theBird;
let yellowBird;
let purpleBird;
